// src/context/LanguageContext.jsx
import { createContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

const translations = {
  RU: {
    category: "Каталог",
    main: "Главная",
    catalog: "Catalog",
    count: "Сум",
    back: 'Назад в каталог',
    Add: "Добавить в корзину",
    total: "Итого",
    shipping: "Стоимость доставки рассчитывается при оформлении заказа.",
    checkout: "Оформить заказ",
    continue: "Продолжить покупки",
    or: "или",
    remove: "Удалить",
    quantity: "Количество:",
    empty: "Корзина пуста",
    emptyCartPrompt: "Добавьте товары в корзину перед оформлением заказа",
    goToCatalog: "Перейти в каталог",
    added: "Товар добавлен в корзину!",
    aded: "Добавлено!",
    cart: "Корзина",
    heroDescription: "Роскошные свечи ручной работы из премиального соевого воска. Создайте моменты спокойствия с нашей тщательно подобранной коллекцией изысканных ароматов.",
    hour: "48 Часов",
    happy: "Счастливые клиенты",
    natural: "Натуральные ингредиенты",
    delivery: "Время доставки",
    iluminate: "Осветите ваше пространство",
    freeshipping: "Бесплатная доставка при заказе от $50",
    shopcollection: "Наш каталог",
    learnourstory: "О нас",
    who: "Кто мы", 
    must: "* — Обязательный пункт заполнения",
    new: "Новинки",
    new2: "Новинка",
    hit: "Хит продаж",
    hit2: "Хит",
    loadingCatalog: "Загрузка каталога...",
    poumolchaniyu: "По умолчанию",
  findPerfectCandle: "Найдите идеальную свечу для вашего дома",
  notFound: "Товары не найдены",
  popular: "Популярные товары",
  select: "Выберите из наших лучших свечей",
  searchPlaceholder: "Поиск по названию, описанию или аромату...",
  sortByDefault: "По умолчанию",
  sortByPriceAsc: "Цена: по возрастанию",
  sortByPriceDesc: "Цена: по убыванию",
  sortByNameAsc: "По названию (А–Я)",
  sortByNewest: "Сначала новые",
  allProducts: "Все товары",
  bestsellers: "Лидеры продаж",
  newArrivals: "Новинки",
  sales: "Распродажи",
  foundProducts: "Найденные товары",
  noImage: "Изображение отсутствует",
  sale: "Акция",
  aroma: "Аромат",
  tryChangeFilters: "Попробуйте изменить поиск или фильтры",
  resetFilters: "Сбросить фильтры",
  noimg: "Изображение отсутствует",
  description: "Описание",
  lookmore: "Посмотреть все товары",
  // 404
  notFoundTitle: "404: Страница не найдена",
  notFoundDesc: "Эта страница не существует или была перемещена.",
firstName: "Имя",
lastName: "Фамилия",
phone: "Телефон",
deliveryMethod: "Способ доставки",
paymentMethod: "Способ оплаты",
shippingDate: "Дата отправки",
orderComment: "Комментарий к заказу",
orderContents: "Содержание заказа",
orderPlacedTitle: "Заказ оформлен ✅",
orderPlacedDesc: "Спасибо! Мы свяжемся с вами для подтверждения.",
close: "Закрыть",
toCatalog: "В каталог",
deliveryOptionCourier: "Курьером",
deliveryOptionPost: "Почтой",
paymentOptionCardTransfer: "Перевод на банковскую карту",
submitProcessing: "Обработка...",
orderSuccessToast: "✅ Заказ успешно оформлен!",
orderErrorToast: "❌ Произошла ошибка при оформлении заказа.",
telegramErrorToast: "❌ Не удалось отправить заказ в Telegram. Пожалуйста, попробуйте позже.",
serverResponseError: "Ошибка ответа сервера",
checkoutTitle: "Оформление заказа",
yourOrder: "Ваш заказ",
selectTypeLabel: "Выберите тип",
selectPlaceholder: "— Выберите —",
// select: "Выберите из наших лучших свечей",
chooseMethod: "Выберите способ",
madein: "Сделано в Узбекистане",
  },
  UZ: {
    category: "Katalog",
    main: "Asosiy",
    catalog: "Catalog",
    count: "Som",
    back: 'Katalogga qaytish',
    Add: "Savatchaga qo'shish",
    shipping: "Yetkazib berish narxi buyurtma berishda hisoblanadi.",
    total: "Jami",
    checkout: "Buyurtma berish",
    continue: "Xaridni davom ettirish",
    or: "yoki",
    remove: "O'chirish",
    quantity: "Miqdor:",
    shoppingCart: "Savatcha",
    empty: "Savatcha bo'sh",
    emptyCartPrompt: "Buyurtma berishdan oldin savatchaga mahsulot qo‘shing",
    goToCatalog: "Katalogga o'tish",
    added: "Mahsulot savatchaga qo'shildi!",  
    aded: "Qo'shildi!",
    cart: "Savatcha",
    heroDescription: "Premium soya mumi bilan qo'lda tayyorlangan hashamatli shamlar. Bizning tanlangan nozik hidlar to'plamimiz bilan tinchlik lahzalarini yarating.",
    hour: "48 Soat",
    happy: "Baxtli mijozlar",
    natural: "Tabiiy ingredientlar",
    delivery: "Yetkazib berish vaqti",
    iluminate: "O'zingizning makoningizni yoritib bering",
    freeshipping: "$50 dan ortiq buyurtmalarda bepul yetkazib berish",
    shopcollection: "Katalogimiz",
    learnourstory: "Bizni haqimizda",
    who: "Biz kimmiz",
    must: "* — Majburiy to'ldirish maydoni",
    new: "Yangi mahsulotlar",
    new2: "Yangi mahsulot",
    hit: "Eng ko'p sotilganlar",
    hit2: "Eng ko'p sotilgan",
    loadingCatalog: "Katalog yuklanmoqda...",
    poumolchaniyu: "Standart boʻyicha",
    findPerfectCandle: "Uylaringiz uchun mukammal shamni toping",
    searchPlaceholder: "Nomi, tavsifi yoki hidi bo‘yicha qidirish...",
    sortByDefault: "Standart",
    sortByPriceAsc: "Narx: pastdan yuqoriga",
    sortByPriceDesc: "Narx: yuqoridan pastga",
    sortByNameAsc: "Nom bo‘yicha (A–Z)",
    sortByNewest: "Yangi mahsulotlar avval",
    allProducts: "Barcha mahsulotlar",
    bestsellers: "Eng ko‘p sotilganlar",
    newArrivals: "Yangi kelganlar",
    sales: "Aksiyalar",
    foundProducts: "Topilgan mahsulotlar",
    noImage: "Rasm mavjud emas",
    sale: "Aksiya",
    aroma: "Hid",
    notFound: "Mahsulot topilmadi",
    tryChangeFilters: "Qidiruv yoki filtrlarni o‘zgartirib ko‘ring",
    resetFilters: "Filtrlarni tiklash",
    noimg: "Rasm mavjud emas",
    allproduscts: "Barcha mahsulotlar",
    lookmore: "Barcha mahsulotlarni ko'rish",
    select: "Bizning eng yaxshi shamlarimizdan tanlang",
    popular: "Mashhur mahsulotlar",
    // 404
    notFoundTitle: "404: Sahifa topilmadi",
    notFoundDesc: "Bu sahifa mavjud emas yoki ko'chirilgan.",
    categoryLabel: "Toifa:",
    aromaLabel: "Hid:",
    burnTimeLabel: "Yong‘ish vaqti:",
    waxCompositionLabel: "Mum tarkibi:",
    cottonWickLabel: "✓ Paxta fitil",
    sizeLabel: "O‘lcham:",
    colorLabel: "Rang:",
    shapeLabel: "Shakl:",
    selectTypeLabel: "Turini tanlang",
    selectPlaceholder: "— Tanlang —",
    description: "Tavsif",
    highlights: "Afzalliklar",
    details: "Batafsil",
    loading: "Yuklanmoqda...",
    pleaseSelectType: "Iltimos, mahsulot turini tanlang",
    productNotFoundError: "Xato: mahsulot topilmadi",
    chooseMethod: "Usulni tanlang",
    checkoutTitle: "Buyurtma berish",
    yourOrder: "Buyurtmangiz",
    firstName: "Ism",
    lastName: "Familiya",
    phone: "Telefon",
    deliveryMethod: "Yetkazib berish usuli",
    paymentMethod: "To‘lov usuli",
    shippingDate: "Jo‘natish sanasi",
    orderComment: "Buyurtma uchun izoh",
    orderContents: "Buyurtma tarkibi",
    orderPlacedTitle: "Buyurtma rasmiylashtirildi ✅",
    orderPlacedDesc: "Rahmat! Tasdiqlash uchun siz bilan bog‘lanamiz.",
    close: "Yopish",
    toCatalog: "Katalogga",
    deliveryOptionCourier: "Kuryer orqali",
    deliveryOptionPost: "Pochta orqali",
    paymentOptionCardTransfer: "Karta orqali o‘tkazma",
    submitProcessing: "Rasmiylashtirilmoqda...",
    orderSuccessToast: "✅ Buyurtma muvaffaqiyatli rasmiylashtirildi!",
    orderErrorToast: "❌ Buyurtma rasmiylashtirishda xatolik yuz berdi.",
    telegramErrorToast: "❌ Buyurtmani Telegramga yuborib bo‘lmadi. Keyinroq urinib ko‘ring.",
    serverResponseError: "Server javobida xatolik",
    madein: "O'zbekistonda ishlab chiqarilgan",
  },
  EN: {
    category: "Catalog",
    main: "Home",
    catalog: "Catalog",
    count: "UZS",
    back: 'Back to catalog',
    Add: "Add to bag",
    shipping: "Shipping cost is calculated at checkout.",
    checkout: "Checkout",
    total: "Subtotal",
    continue: "Continue shopping",
    or: "or",
    remove: "Remove",
    quantity: "Quantity:",
    shoppingCart: "Shopping Cart",
    empty: "Your cart is empty",
    emptyCartPrompt: "Add items to your cart before checking out",
    goToCatalog: "Go to catalog",
    added: "Product added to cart!",
    aded: "Added!",
    cart: "Cart",
    heroDescription: "Handcrafted luxury candles made from premium soy wax. Create moments of tranquility with our curated collection of fine scents.",
    hour: "48 Hours",
    happy: "Happy Customers",
    natural: "Natural Ingredients",
    delivery: "Delivery Time",
    iluminate: "Illuminate Your Space",
    freeshipping: "Free shipping on orders over $50",
    shopcollection: "Our catalog",
    learnourstory: "About us",
    who: "Who we are",
    must: "* — Required field",
    new: "New arrivals",
    new2: "New Arrival",
    hit: "Best sellers",
    hit2: "Bestseller",
    // 404
    notFoundTitle: "404: Not found",
    notFoundDesc: "This page does not exist or has been moved.",
    loadingCatalog: "Loading catalog...",
    poumolchaniyu: "By default",

  // Checkout + Modal
  chooseMethod: "Choose method",
  checkoutTitle: "Checkout",
  yourOrder: "Your order",
  firstName: "First name",
  lastName: "Last name",
  phone: "Phone",
  deliveryMethod: "Delivery method",
  paymentMethod: "Payment method",
  shippingDate: "Shipping date",
  orderComment: "Order comment",
  orderContents: "Order summary",
  orderPlacedTitle: "Order placed ✅",
  orderPlacedDesc: "Thank you! We will contact you to confirm.",
  close: "Close",
  toCatalog: "To catalog",
  deliveryOptionCourier: "By courier",
  deliveryOptionPost: "By post",
  paymentOptionCardTransfer: "Bank card transfer",
  submitProcessing: "Processing...",
  orderSuccessToast: "✅ Order successfully placed!",
  orderErrorToast: "❌ An error occurred while placing the order.",
  telegramErrorToast: "❌ Failed to send order to Telegram. Please try again later.",
  serverResponseError: "Server response error",
  popular: "Popular Products",
  select: "Select from our best candles",
  findPerfectCandle: "Find the perfect candle for your home",
  searchPlaceholder: "Search by name, description, or scent...",
  sortByDefault: "Default",
  sortByPriceAsc: "Price: Low to High",
  sortByPriceDesc: "Price: High to Low",
  sortByNameAsc: "Name (A–Z)",
  sortByNewest: "Newest arrivals",
  allProducts: "All Products",
  bestsellers: "Bestsellers",
  newArrivals: "New Arrivals",
  sales: "Promotions",
  foundProducts: "Found Products",
  noImage: "No image available",
  sale: "Promotion",
  aroma: "Scent",
  notFound: "Products not found",
  tryChangeFilters: "Try changing your search or filters",
  resetFilters: "Reset filters",
  noimg: "No image available",
  description: "Description",
  lookmore: "View all products",
madein: "Made in Uzbekistan",
  }
 
};



export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("RU");
  const [texts, setTexts] = useState(translations["RU"]);

  useEffect(() => {
    const savedLang = localStorage.getItem("language");
    if (savedLang && translations[savedLang.toUpperCase()]) {
      setLanguage(savedLang.toUpperCase());
      setTexts(translations[savedLang.toUpperCase()]);
    }
  }, []);

  const changeLanguage = (lang) => {
    const upperLang = lang.toUpperCase();
    if (translations[upperLang]) {
      setLanguage(upperLang);
      setTexts(translations[upperLang]);
      localStorage.setItem("language", upperLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, texts, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
